Soma
Edu4rdob/Avalia-oFireman pull request #9
Opened 2021-09-07 21:53 UTC by Edu4rdob

2021-09-07 23:36 UTC, Marianacris2 requested changes

2021-09-07 23:36 UTC, Marianacris2 commented on calc-api/src/main/java/app/App.java
> +    mvc(new Soma());
Muito legal ter a função soma e a função subtração, Eduardo! Seria legal também fazer outras funções matemáticas juntamente das duas!!

2021-09-07 23:41 UTC, Marianacris2 approved these changes

2021-09-13 23:01 UTC, Edu4rdob commented on calc-api/src/main/java/app/App.java
> +    mvc(new Soma());
Pronto, vou deixar anotado aqui. Obrigado, srta. Mariana!!

2021-09-13 23:01 UTC, merged